# ==========================================
# SERVER
# ==========================================

server.port=8080


# ==========================================
# PYTHON WORKER
# ==========================================

worker.python=/usr/bin/python3
worker.script=/home/vortexis/RegisV8_Fix/main.py
worker.accounts=/home/vortexis/RegisV8_Fix/accounts
worker.links=/home/vortexis/RegisV8_Fix/link.txt


# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/regis
spring.datasource.username=regis
spring.datasource.password=Admin1sampai5@5sampai1@Vortexis

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


# ==========================================
# JWT
# ==========================================

security.jwt.issuer=regis-api
security.jwt.expiration-seconds=900


# ==========================================
# VALIDATION
# ==========================================

spring.mvc.throw-exception-if-no-handler-found=true


# ==========================================
# JSON
# ==========================================

spring.jackson.serialization.write-dates-as-timestamps=false

# ==========================================
# CORS
# ==========================================

app.cors-origin=https://yukregis.site
