spring.application.name=regis-backend

server.port=8080


# ===============================
# PYTHON WORKER
# ===============================

worker.python=/opt/regis/venv/bin/python

worker.script=/opt/regis/main.py


# ===============================
# INPUT FILE
# ===============================

worker.links=/opt/regis/link.txt

worker.accounts=/opt/regis/accounts.txt


# ===============================
# LIMIT
# ===============================

worker.max-concurrency=50

worker.max-timeout-seconds=300


# ===============================
# CORS
# ===============================

app.cors-origin=http://localhost:5173